[SQUASH] Import build/target/product/ changes from LineageOS vendor
commit 8bda0bf62b97c795ba5016da88ad4e0fab37472b
Author: Kilian von Pflugk <github@jumoog.io>
Date:   Mon Dec 10 12:31:27 2018 +0100

    products: bliss_{gsi,sdk}_tv*: Remove TARGET_USES_64_BIT_BINDER

    The TARGET_USES_64_BIT_BINDER option is deprecated and can be removed

    Change-Id: I6b828da1fbcc8c054c5b35ff78c870a689f7ed9f

commit 5b8dd24b8e7ecbc2bd6ac619011dea40293e743d
Author: mse1969 <mse1969@posteo.de>
Date:   Tue Mar 26 22:33:05 2024 +0100

    bliss: products: sdk_phone_x86_64 emulator - fix sdk_addon packaging

    With the merge of tag 'android-14.0.0_r29', the emulator sdk_phone_x86_64
    is inherited from device/generic/goldfish. This means, that the component
    PRODUCT_SDK_ADDON_COPY_FILES needs to be defined here.

    Change-Id: I2cee21d27f28521f34e80262c2abda6b7eb3360c

commit 105b86ee09b43a15d2eb74ba41a0e58e816efe03
Author: mse1969 <mse1969@posteo.de>
Date:   Mon Mar 25 17:11:04 2024 +0100

    bliss: products: sdk_phone_x86_64 emulator - restore partition sizes

    With the merge of tag 'android-14.0.0_r29', the emulator sdk_phone_x86_64
    is inherited from device/generic/goldfish. Its defined super partition
    size of 1.6GB however is too small to build the Bliss 21 emulator.

    Therefore, overwrite the partition sizes with the values as previously
    set in build/make/target/board/BoardConfigEmuCommon.mk

    Change-Id: Ib8443cb3d8cacb42cab68f154845574fadf99b55

commit 01a36e1909ef6617d2696b0fad46c2b5ab8bb5e1
Author: mse1969 <mse1969@posteo.de>
Date:   Sun Mar 24 23:20:28 2024 +0100

    bliss: products: remove sdk_phone_x86 emulator target

    necessary after merge of tag 'android-14.0.0_r29':

     e04167e Retire obsolete (32bit-only) emulator targets and boards

     Please use 64bit-only targets instead:
     [...]  * we don't support x86+arm for AOSP targets

    Change-Id: I001b97e218f837005d4283bd0540519b00301783

commit b0d0c6fa41017011fc13755347c22a865c233ba0
Author: mse1969 <mse1969@posteo.de>
Date:   Sun Mar 24 23:15:40 2024 +0100

    bliss: products: Fix bliss_sdk_car* emulator targets

    necessary after merge of tag 'android-14.0.0_r29':

     228de7b Remove sdk_<arch> products

     The SDK is arch-agnostic, so does not need per-arch products.

    Change-Id: Idac94e841e749d6dcc4aa643b8738f8c07ac71fa

commit 1c69ed407e0f023c5f03664284d23a8651599ed6
Author: mse1969 <mse1969@posteo.de>
Date:   Sun Mar 24 15:37:31 2024 +0100

    bliss: products: Fix bliss_sdk_phone_x86_64 emulator target

    necessary after merge of tag 'android-14.0.0_r29':

     4bf479f Retire obsolete emulator targets and boards

     the sdk_phone* targets are replaced with sdk_phone64*,
     the emulator* boards are replaced with emu64* in
     the device/generic/goldfish folder.

    Change-Id: Ie36e73684d586223bbce642a62cf155a3990713e

commit 9fe4bc8a605fe43f24dbc42ff83babfae8379da2
Author: DroidFreak32 <rushabshah32@gmail.com>
Date:   Mon Feb 12 11:28:40 2024 +0530

    bliss: products: Bring back bliss_sdk_phone_arm64 emulator target

    Change-Id: I0578608bd78e1a03f90b17de4ee558646ce9ef2f

commit d7fa6a32e2ab84be54ec47427bfef2c429520035
Author: DroidFreak32 <rushabshah32@gmail.com>
Date:   Sat Apr 22 15:50:22 2023 +0530

    bliss: Fix SDK Addon build on x86/x86_64 targets

    - Fixes the following build error:

    100% 1/1] analyzing Android.bp files and generating ninja file at ou
    FAILED: out/soong/build.ninja
    cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     -o out/soong/build.ninja --globListDir build --globFile out/soong/globs-build.ninja -t -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.build Android.bp
    error: packages/modules/RuntimeI18n/apex/Android.bp:67:1: dependency "art-bootclasspath-fragment" of "i18n-bootclasspath-fragment" missing variant:
      apex:com.android.art
    available variants:
      os:android,arch:common
    error: packages/modules/RuntimeI18n/apex/Android.bp:67:1: dependency "prebuilt_art-bootclasspath-fragment" of "i18n-bootclasspath-fragment" missing variant:
      apex:com.android.art
    available variants:
      os:android,arch:common
    15:24:42 soong bootstrap failed with: exit status 1

     #### failed to build some targets (19 seconds) ####

    Change-Id: Iff5aa79b4148f83680bc33bdd0ea9751038feea1

commit 68544f936f7c0544c1f3e3a00b83d20337b26704
Author: althafvly <althafvly@gmail.com>
Date:   Fri Jun 24 15:44:16 2022 +0530

    bliss: products: Un-break SDK addon

    - Fixes error while building
      Trying to build sdk_addon, but product 'vendor/bliss/build/target/product/bliss_sdk_phone_x86_64.mk' does not define one
    - Move gsi_release.mk to gsi_tv_arm*.mk. SDK and x86* targets won't build.
    - Set TARGET_SUPPORTS_64_BIT_APPS for x86_64 gsi to support both arch apps.

    Change-Id: If01e2eecfc5e27a98e696c29f29babbc1a5ec726

commit 8db975cd360f472a954e84016f81ade17d08f870
Author: Nolen Johnson <johnsonnolen@gmail.com>
Date:   Mon Mar 14 16:51:46 2022 -0400

    bliss: products: Rename ATV targets to reflect AOSP GSI names

    Change-Id: I96a28e5beaffd9148be2ddb379f8990c172ca69f

commit 4d09aac1ecf8afcb841273973124a66715c03fa0
Author: Nolen Johnson <johnsonnolen@gmail.com>
Date:   Mon Feb 14 17:38:30 2022 -0500

    bliss: products: Create new Automotive GSI targets

    * And split out emulator includes as needed to do so.

    Change-Id: I9a9e02dc9ebf4613bf2da6be9985a8565dac93fc

commit c86992e0cd80ea4790d37dd74c3a917efc310660
Author: Tom Pratt <tom.pratt@outlook.com>
Date:   Thu Mar 3 10:54:03 2022 +0100

    Fix GSI targets

    Inherit from AOSP gsi_{arch}.mk, because aosp_{arch}.mk files
    are obsolete in Android 12. Rename for consistency with
    AOSP gsi/sdk targets.

    Change-Id: I449390521307ff4f269a9ebf1ad3a5ffc398bc97

commit d0b3a4af0f4a02cccd73666b3fba787aeb9a2248
Author: Nolen Johnson <johnsonnolen@gmail.com>
Date:   Mon Feb 14 16:59:29 2022 -0500

    bliss: products: Add ATV emulator targets

    * device/google/atv only supports armv7 and x86, so
      for emulator at least, we will too.

    Change-Id: I5c7f00f8dd34d9d95747d05b6c091376451cc986

commit 8e215b72000a65d4b068d3be135d43bfbc96f40a
Author: Nolen Johnson <johnsonnolen@gmail.com>
Date:   Mon Feb 14 15:59:04 2022 -0500

    bliss: products: bliss_x86{,_64}: Don't build kernel

    * Results in an error.

    Change-Id: Ifab94ca34bab75d8e55b317f69060fc02f068ecf

commit d8bdaefb4f13de808f574c3ff52df2d8883b7575
Author: Nolen Johnson <johnsonnolen@gmail.com>
Date:   Mon Feb 14 15:57:50 2022 -0500

    bliss: products: bliss_x86{,_64}: Don't include SDK addon

    * This doesn't work, and just errors out similar to arm/arm64.

    Change-Id: I53a2261095f1e2acab3b7da20d3f092ccc83e8ab

commit 5a35edd014364fb26624d5fc05e001e4d318718b
Author: Tom Pratt <tom.pratt@outlook.com>
Date:   Thu Feb 10 17:06:29 2022 +0100

    Rename automotive emulator targets

    Matches the upstream separation of gsi and emulator targets.

    Change-Id: I07947727c39b87d2bd1ee6bf2809a7f40ff380ba

commit a427f4384829fd0c8a9b65019efb57f9aed0cfc3
Author: Michael Bestas <mkbestas@gmail.com>
Date:   Sat Nov 13 03:14:47 2021 +0200

    build: Enable mainline checking for GSI/emulator targets

    * This is originally done in build/make but it checks against aosp_* targets
    * Enable it for all of our bliss_* targets

    Change-Id: I9fa62c8f709bd649d114f24f241d42d471489ae5

commit 33384ced538569c901e36bd17b37c22cc5033027
Author: Tom Pratt <tom.pratt@outlook.com>
Date:   Tue Nov 23 12:50:08 2021 +0100

    Use sdk_{arch}.mk as base for automotive emulator targets

    It no longer boots using aosp_{arch}.mk and aosp targets all
    use sdk_{arch}.mk now.

    Change-Id: I2f6c644353966a58299fbdfa42c7fd3b0d5dea90

commit baab5a81f5e6e8ce071d06d23aa79a2ca5cccc98
Author: Michael Bestas <mkbestas@gmail.com>
Date:   Sat Nov 13 03:12:55 2021 +0200

    build: Remove legacy GSI targets

    * Support for these targets is no longer present in build/make

    Change-Id: I2b07ca52c3040f8b1592dd9760ca2357105e082d

commit 253f90404d7c9f8a1fc44b1e5e24ed6205d376d8
Author: Michael Bestas <mkbestas@gmail.com>
Date:   Mon May 24 20:57:21 2021 +0300

    build: Add x86/x86_64 emulator targets

    Change-Id: Ic8789ad2072b9ebda91f9b4a7c288a5a9bcec3fd

commit c63ee5cc9c86fa3849f792adb05be44bf4ea0ae6
Author: Michael Bestas <mkbestas@gmail.com>
Date:   Fri Jun 11 19:32:26 2021 +0300

    Don't copy privapp-permissions-goldfish.xml for GSI targets

    * It is already copied to product partition through AOSP makefiles

    Change-Id: I9d877728decc712ce6ae5cc285b1b6a7a4903daf

commit de83dffc3476ac7eb0c47da3aa85892766403a43
Author: Tom Pratt <tom.pratt@outlook.com>
Date:   Mon Jul 12 12:34:22 2021 +0200

    Add generic targets for automotive

    Makefiles combining core bliss and automotive packages.
    Can be included by devices to turn them into Automotive builds.
    Emulator targets demonstrate using these makefiles and form a basis for Automotive GSIs.
    Change-Id: Ib5d35dfe4de8c459e4e14a7ba6f0b0e682e0d912

commit db313846b10f9c6d7ce8a50372508aaa2e92855c
Author: Nolen Johnson <johnsonnolen@gmail.com>
Date:   Tue Mar 9 22:15:54 2021 +0100

    bliss: targets: x86{,_64}_ab: Don't explicitly include SDK addon

    * This resolves some build warnings on these targets, as it's
      being declared elsewhere.

    Change-Id: If142b7435d8f4b81f8477516545bb54462518487

commit 52be5fcb104cc60c34c6459e05f89a33281e80d0
Author: Nolen Johnson <johnsonnolen@gmail.com>
Date:   Tue Mar 9 14:10:39 2021 -0500

    bliss: targets: Add support for Legacy GSIs

    * This is needed for VNDK27, and other older,
      hackier Treble implementations.

    * We can't include `legacy_gsi_release.mk` as it's included
      in the `aosp_${ARCH}_ab` targets themselves, unlike the standard
      `aosp_${ARCH}` targets which guard `gsi_release.mk`'s inclusion
       with `aosp_${ARCH}` product guards.

    Change-Id: I16c5983c18110b24eef84e382e0ae6852efb03c3

commit c2d63c642e38b74a8559f0eebf7ae28f631b83bf
Author: Nolen Johnson <johnsonnolen@gmail.com>
Date:   Tue Dec 8 16:31:31 2020 -0500

    bliss: targets: Add support for ATV GSI builds

    Change-Id: I1faf83e21af5db1b29b98af72a4f74666c05f775

Co-authored-by: Kilian von Pflugk <github@jumoog.io>
Co-authored-by: mse1969 <mse1969@posteo.de>
Co-authored-by: DroidFreak32 <rushabshah32@gmail.com>
Co-authored-by: althafvly <althafvly@gmail.com>
Co-authored-by: Nolen Johnson <johnsonnolen@gmail.com>
Co-authored-by: Tom Pratt <tom.pratt@outlook.com>
Co-authored-by: Michael Bestas <mkbestas@gmail.com>
Signed-off-by: Jackeagle <jackeagle102@gmail.com>